import fs from 'fs';
import path from 'path';
import * as cheerio from 'cheerio';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.join(__dirname, '..');
const TOOLS_DIR = path.join(ROOT_DIR, 'tools');

function getHtmlFiles(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const stat = fs.statSync(path.join(dir, file));
    if (stat.isDirectory()) {
      getHtmlFiles(path.join(dir, file), fileList);
    } else if (file.endsWith('.html') && file !== 'index.html') {
      // Skip category index.html pages as they are generated by sync-all.js usually
      fileList.push(path.join(dir, file));
    }
  }
  return fileList;
}

const allTools = getHtmlFiles(TOOLS_DIR);
let migrated = 0;

for (const filePath of allTools) {
  const html = fs.readFileSync(filePath, 'utf8');

  // If it doesn't look like a full HTML document anymore, skip it
  if (!html.includes('<html') && !html.includes('<!DOCTYPE') && !html.includes('<!doctype')) {
    continue;
  }

  const $ = cheerio.load(html);

  let styles = '';
  $('style').each((i, el) => {
    styles += $(el).html().trim() + '\n';
  });

  let bodyContent = '';
  const main = $('main.tool-main');
  if (main.length > 0) {
    bodyContent = main.html().trim();
  } else {
    const container = $('body > .container, body > .cat-main, body > main');
    if (container.length > 0) {
      bodyContent = container.parent().html(); // We actually want the container itself for PR 152 tools
      // Wait, .html() of parent gives the whole body? Yes, we can just extract the container element
      bodyContent = $.html(container);
    } else {
      $('body > script').remove();
      $('body > a[href="../../index.html"]').remove();
      $('body > header.site-header').remove();
      $('body > footer.site-footer').remove();
      $('body > nav.sidebar').remove();
      $('body > div.sidebar-overlay').remove();
      bodyContent = $('body').html().trim();
    }
  }

  let scripts = '';
  $('script:not([src])').each((i, el) => {
    let scriptContent = $(el).html().trim();
    if (
      !scriptContent.includes('application/ld+json') &&
      !scriptContent.includes('const prefersDark') &&
      !scriptContent.includes('umami.track') &&
      !scriptContent.includes('function initTheme()')
    ) {
      scripts += scriptContent + '\n\n';
    }
  });

  // Reconstruct fragment
  let fragment = '';
  if (styles.trim()) {
    fragment += `<style>\n${styles.trim()}\n</style>\n\n`;
  }
  fragment += bodyContent + '\n\n';
  if (scripts.trim()) {
    fragment += `<script>\n${scripts.trim()}\n</script>\n`;
  }

  fs.writeFileSync(filePath, fragment.trim() + '\n');
  migrated++;
}

console.log(`✅ Successfully migrated ${migrated} full HTML files to fragments.`);
